# Generated by Django 5.0.7 on 2024-07-28 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='tag',
            new_name='tags',
        ),
    ]
